"""
Font atlas generator - Creates PPM image and C++ header from TTF font.
Requires: pip install freetype-py numpy
"""

import struct
from pathlib import Path
from typing import Tuple, Dict
import freetype

def render_font_atlas(
    ttf_path: Path,
    font_size: int,
    output_ppm: Path,
    output_header: Path,
    characters: str = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
) -> None:
    """
    Render all characters to a PPM image and generate C++ header with glyph metadata.
    """
    # Initialize FreeType
    library = freetype.Face(str(ttf_path))
    library.set_pixel_sizes(0, font_size)
    
    # Calculate atlas dimensions (simple row-by-row packing)
    char_data: Dict[str, dict] = {}
    max_height = 0
    current_x = 0
    current_y = 0
    row_height = 0
    
    # First pass: measure all characters
    for char in characters:
        library.load_char(char)
        glyph = library.glyph
        bitmap = glyph.bitmap
        
        width = bitmap.width
        height = bitmap.rows
        bearing_x = glyph.bitmap_left
        bearing_y = glyph.bitmap_top
        
        # Advance (horizontal spacing)
        advance = glyph.advance.x >> 6  # Convert from 26.6 fixed point
        
        char_data[char] = {
            'width': width,
            'height': height,
            'bearing_x': bearing_x,
            'bearing_y': bearing_y,
            'advance': advance,
            'buffer': bytes(bitmap.buffer)
        }
        
        max_height = max(max_height, height)
        row_height = max(row_height, height)
        
        if current_x + width > 2048:  # Max atlas width
            current_x = 0
            current_y += row_height + 2
            row_height = 0
        
        current_x += width + 2
    
    # Calculate final atlas size
    atlas_width = max(current_x + 2, 1)
    atlas_height = current_y + row_height + 2
    
    # Second pass: create atlas image (grayscale, stored as RGB for PPM)
    atlas = bytearray(atlas_width * atlas_height * 3)  # RGB
    
    current_x = 0
    current_y = 0
    row_height = 0
    
    for char in characters:
        data = char_data[char]
        width = data['width']
        height = data['height']
        bearing_x = data['bearing_x']
        bearing_y = data['bearing_y']
        
        # Position in atlas (accounting for bearing)
        dest_x = current_x + bearing_x
        dest_y = current_y + (row_height - bearing_y)
        
        # Copy bitmap data to atlas (grayscale to RGB)
        for py in range(height):
            for px in range(width):
                if px < width and py < height:
                    idx = (py * width + px)
                    pixel_value = data['buffer'][idx]
                    
                    # Write to atlas (RGB format)
                    atlas_idx = ((dest_y + py) * atlas_width + (dest_x + px)) * 3
                    if 0 <= dest_x + px < atlas_width and 0 <= dest_y + py < atlas_height:
                        atlas[atlas_idx] = pixel_value
                        atlas[atlas_idx + 1] = pixel_value
                        atlas[atlas_idx + 2] = pixel_value
        
        # Update position
        row_height = max(row_height, height)
        current_x += width + 2
        
        if current_x + 2 > 2048:
            current_x = 0
            current_y += row_height + 2
            row_height = 0
    
    # Write PPM P3 (ASCII) format
    ppmp3 = f"P3\n{atlas_width} {atlas_height}\n255\n"
    for y in range(atlas_height):
        for x in range(atlas_width):
            idx = (y * atlas_width + x) * 3
            r = atlas[idx]
            g = atlas[idx + 1]
            b = atlas[idx + 2]
            ppmp3 += f"{r} {g} {b} "
        ppmp3 += "\n"

    with open(output_ppm, 'w') as f:
        f.write(ppmp3)
    
    # Generate C++ header
    header_content = f'''// Auto-generated font atlas header - DO NOT EDIT
// Generated by 'Scripts/generate_font.py' from '{ttf_path.name}'
// Font size: {font_size}px
// Characters: {len(characters)}

#pragma once

#include <unordered_map>
#include <string_view>

#include <glm/glm.hpp>

namespace font {{

constexpr std::string_view FONT_ATLAS = "{ppmp3.replace("\n", "\\n")}";

static const std::unordered_map<char, glm::vec2> GLYPH_MAP = {{
'''
    
    current_x = 0
    current_y = 0
    row_height = 0
    
    for char in characters:
        data = char_data[char]
        width = data['width']
        height = data['height']
        bearing_x = data['bearing_x']
        bearing_y = data['bearing_y']
        
        # Calculate atlas position
        dest_x = current_x + bearing_x
        dest_y = current_y + (row_height - bearing_y)
        
        # Normalize UV coordinates (0-1 range)
        u_min = dest_x / atlas_width
        v_min = dest_y / atlas_height
        u_max = (dest_x + width) / atlas_width
        v_max = (dest_y + height) / atlas_height
        
        # glm::vec2(x, width) - in UV space
        header_content += f'    {{\'{escape_char(char)}\', glm::vec2({u_min:.6f}, {u_max - u_min:.6f})}},\n'
        
        row_height = max(row_height, height)
        current_x += width + 2
        
        if current_x + 2 > 2048:
            current_x = 0
            current_y += row_height + 2
            row_height = 0
    
    header_content += '''};

} // namespace font
'''
    
    with open(output_header, 'w') as f:
        f.write(header_content)
    
    print(f"Generated: {output_ppm} ({atlas_width}x{atlas_height})")
    print(f"Generated: {output_header}")


def escape_char(c: str) -> str:
    """Escape special characters for C++ string literal."""
    escapes = {
        '\\': '\\\\',
        '"': '\\"',
        "'": "\\'",
        '\n': '\\n',
        '\t': '\\t',
        '\r': '\\r',
    }
    return escapes.get(c, c)


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) != 4:
        print("Usage: python font_generator.py <font.ttf> <size> <output_dir>")
        sys.exit(1)
    
    ttf = Path(sys.argv[1])
    size = int(sys.argv[2])
    out_dir = Path(sys.argv[3])
    out_dir.mkdir(parents=True, exist_ok=True)
    
    render_font_atlas(
        ttf_path=ttf,
        font_size=size,
        output_ppm=out_dir / "FontAtlas.ppm",
        output_header=out_dir / "FontAtlas.h"
    )
